### ISSUE TITLE
feature/etc

### ISSUE THREAD

**Issue by kgw0124** [Hanaro-FX/Hanaro-FX#29]
## ✔️ TODO

- [x] 포트폴리오 생성 시(/create), 리밸런싱 주기 삭제
- [x] 포트폴리오 생성 완료 시(/create), 상세 페이지로 리다이렉트하기
- [ ] 포트폴리오 생성 시(/result), 특정 값 삭제하면 total 값에 반영하기
- [x] 포트폴리오 생성 시(/result), 조건을 선택하지 않고 생성하면 alert() 띄우기
- [x] 제목 없는 포트폴리오 상세 조회 시, nameSpace에 "제목 없는 포트폴리오"로 띄우기
- [x] 로그인/로그아웃 버튼 style 수정
