### ISSUE TITLE
feature/update portfolio-result css

### ISSUE THREAD

**Issue by soyeonvv** [Hanaro-FX/Hanaro-FX#36]
## 📝 기능 개요

포트폴리오 상세(결과) 페이지 CSS 수정

## ✔️ TODO

- [x] 표 순서 바꾸기
- [x] 표 숨기기 (test 버튼 클릭시 나타나기)
- [x] 수정 아이콘 추가
- [x] 목록으로 아이콘 추가
- [x] 날짜 유효성 검사 로직 수정
- [x] 카카오 공유창 option 수정
